[tool.poetry]
name = "prog1"
version = "0.1.0"
description = ""
authors = ["Wisia"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ascii_graph = "^1.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
